Refactor all the tests.
hpi-swa-teaching/TogglClient pull request #70
Opened 2019-07-25 12:56 UTC by phoeinx

2019-07-25 16:09 UTC, leowe requested changes

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglAccountSettings.class/instance/buildWith..st
> +		extent: self defaultExtent;
is that used somewhere else? otherwise it looks like unnecessary complexity

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/README.md
> +Provides UI and logic for displaying a Toggl client in Squeak
"displaying a Toggl client" - what does that mean? how do you display a client? also Toggl is written with a capital t whereas in the other comments it is written with a lowercase t

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/actionLoginLogout.st
> +		ifTrue: [self logout]
logout is not the only thing that happens there, more descriptive title would be good. logoutAndCleanTimeEntryList or something like this

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/authenticated..st
> +initialize-release
wrong category, should be accessing

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/authenticated.st
> +initialize-release
same

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/defaultExtent.st
> +toolbuilder
inconsistent categorisation with other default extent + magic number encapsulation

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/buildWith..st
> -		extent: 500 @ 400;
still not a fan

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/logout.st
> +toolbuilder
wrong category

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/logout.st
> +toolbuilder
naming problem still holds

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglClient.class/instance/wantsSteps.st
> +testing
seems like the wrong category

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglJsonParser.class/README.md
> +Converts json strings to TogglTimeEntries and back
... and the other way around

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglTimeEntry.class/README.md
> +Represents a time tracking entry in toggl.
first time a dot at the end

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Core.package/TogglTimeEntry.class/instance/renameTo..st
> +testing
testing seems really wrong

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Tests.package/TogglAPITests.class/instance/testAuthenticationSucceedsWithValidAccount.st
> +	self assert: response isSuccess.
dot at the end

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Tests.package/TogglAPITests.class/instance/testPushLocalTimeEntriesSychronizesLocalTimeEntries.st
> +				userName: self validAccountUser;
indentation seems off

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Tests.package/TogglTimeEntryTests.class/instance/testTimeEntrySmallerThanAnotherTimeEntry.st
> +	self assert: finishedTimeEntry < startedTimeEntry.
dot at the end

2019-07-25 16:09 UTC, leowe commented on packages/TogglClient-Tests.package/TogglTimeEntryTests.class/instance/testTimeEntrySmallerThanOrEqualThanAnotherTimeEntry.st
> +	self assert: finishedTimeEntry <= startedTimeEntry.
dot at the end

2019-07-25 21:26 UTC, ma-ro commented on packages/TogglClient-Core.package/TogglClient.class/instance/actionLoginLogout.st
> +		ifTrue: [self logout]
done

2019-07-25 21:29 UTC, ma-ro commented on packages/TogglClient-Core.package/TogglClient.class/README.md
> +Provides UI and logic for displaying a Toggl client in Squeak
feel free to add alternative class comment

2019-07-26 11:16 UTC, phoeinx commented on packages/TogglClient-Core.package/TogglAccountSettings.class/instance/buildWith..st
> +		extent: self defaultExtent;
das heißt wir bleiben bei defaultExtent?

2019-07-26 13:41 UTC, leowe approved these changes

2019-07-26 13:42 UTC, merged